DROP DATABASE IF EXISTS PROYECTO_FIBRA;

CREATE DATABASE PROYECTO_FIBRA;
USE PROYECTO_FIBRA;

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
ITEM VARCHAR (200) not null,
PRECIO_VENTA DECIMAL,
PRECIO_COMPRA DECIMAL
);

CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
CLIENTE VARCHAR  (100),
TELEFONO VARCHAR (20),
MAIL VARCHAR (50),
PAIS VARCHAR (25)
);

CREATE TABLE PROVEEDORES(
ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
PROVEEDOR VARCHAR (100),
TELEFONO VARCHAR (20),
MAIL VARCHAR (50)
);

CREATE TABLE ORDEN_VENTA(
ID_VENTA INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCTO INT,
ID_CLIENTE INT, 
PRECIO_VENTA DECIMAL (10,2),
CANTIDAD INT,
MONTO DECIMAL (10,2),
ID_VENDEDOR INT,
FECHA DATE
);

CREATE TABLE ORDEN_COMPRA(
ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCTO INT,
ID_PROVEEDOR INT, 
PRECIO_COMPRA DECIMAL(10,2),
CANTIDAD INT,
MONTO DECIMAL (10,2),
FECHA DATE
);

CREATE TABLE FACTURAS_VENTAS(
ID_FCVENTA INT PRIMARY KEY AUTO_INCREMENT,
ID_VENTA INT,
MONTO DECIMAL(10,2),
ID_VENDEDOR INT,
FECHA_FACTURA DATE
);

CREATE TABLE FACTURAS_COMPRAS(
ID_FCCOMPRA INT PRIMARY KEY AUTO_INCREMENT,
ID_COMPRA INT,
MONTO DECIMAL(10,2),
FECHA_FACTURA DATE
);

CREATE TABLE PAGOS(
ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
ID_FCCOMPRA INT,
MONTO DECIMAL,
FECHA_PAGO DATE
);


CREATE TABLE COBROS(
ID_COBRO INT PRIMARY KEY AUTO_INCREMENT,
ID_FCVENTA INT, 
MONTO DECIMAL,
FECHA_COBRO DATE
);

CREATE TABLE VENDEDORES(
ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100)
    );
    
    -- FOREIGN KEYS DEFINITION
    
    -- ORDEN_VENTA

    ALTER TABLE ORDEN_VENTA
    ADD CONSTRAINT FK_VENTA_PRODUCTO
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);
    
    ALTER TABLE ORDEN_VENTA
    ADD CONSTRAINT FK_VENTA_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
    
    ALTER TABLE ORDEN_VENTA
    ADD CONSTRAINT FK_VENTA_VENDEDOR
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR);
    
    -- ORDEN_COMPRA
    
    ALTER TABLE ORDEN_COMPRA
    ADD CONSTRAINT FK_COMPRA_PRODUCTO
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);
    
      ALTER TABLE ORDEN_COMPRA
    ADD CONSTRAINT FK_COMPRA_PROVEEDOR
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR);
    
    -- FACTURAS_VENTAS
    
     ALTER TABLE FACTURAS_VENTAS
    ADD CONSTRAINT FK_FCVENTAS_ORDEN
    FOREIGN KEY (ID_VENTA) REFERENCES ORDEN_VENTA(ID_VENTA);
    

         ALTER TABLE FACTURAS_VENTAS
    ADD CONSTRAINT FK_FCVENTAS_VENDEDOR
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR);
    
    -- FACTURAS_COMPRAS
    
    
       ALTER TABLE FACTURAS_COMPRAS
    ADD CONSTRAINT FK_FCCOMPRAS_ORDEN
    FOREIGN KEY (ID_COMPRA) REFERENCES ORDEN_COMPRA(ID_COMPRA);
    
    -- COBROS
     ALTER TABLE COBROS
    ADD CONSTRAINT FK_COBROS_FACTURAS
    FOREIGN KEY (ID_FCVENTA) REFERENCES FACTURAS_VENTAS(ID_FCVENTA);
    

-- PAGOS

 ALTER TABLE PAGOS
    ADD CONSTRAINT FK_PAGOS_FACTURAS
    FOREIGN KEY (ID_FCCOMPRA) REFERENCES FACTURAS_COMPRAS(ID_FCCOMPRA);
